permalink: pretty
markdown: kramdown

title: Dwa składniki w Polsce
author: Josh Davis &amp; Adam Dobrawy
description:
    Lista stron z obsługą dwóch składników uwierzytelniania, czyli wiadomości SMS, e-mail,
     rozmowy telefoniczne, sprzętowe i programowe tokeny.
url: https://ad-m.github.io/dwa-skladniki/
repo: https://github.com/ad-m/dwa-skladniki
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
